name: Build Minecraft Legacy Console Edition (Linux)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    strategy:
      matrix:
        configuration: [Debug]

    steps:
      - name: Install base dependencies
        run: |
          pacman -Syu --noconfirm archlinux-keyring
          pacman -Syu --noconfirm base-devel sudo git clang lld ninja cmake extra-cmake-modules python wine msitools ca-certificates libwbclient

      - name: Create build user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fix permissions
        run: chown -R builder:builder .

      - name: Setup MSVC
        run: |
          git clone https://github.com/mstorsjo/msvc-wine /home/builder/msvc-wine
          cd /home/builder/msvc-wine
          python vsdownload.py --accept-license --dest /home/builder/msvc
          ./install.sh /home/builder/msvc
          chown -R builder:builder /home/builder/msvc
          echo "WINDOWS_SDK_PATH=/home/builder/msvc" >> $GITHUB_ENV

      - name: Wine init
        run: sudo -u builder HOME=/home/builder wine wineboot

      # rm: via act theres an error where CMake was unable to find a build program corresponding to "Ninja"
      - name: Build
        run: |
          sudo -E -u builder sh -ec '
            HOME=/home/builder
            export PATH=$WINDOWS_SDK_PATH/bin/x64:$PATH
            cd $GITHUB_WORKSPACE
            mkdir build && cd build
            cmake .. -B . -GNinja \
              -DCMAKE_MAKE_PROGRAM=$(which ninja) \
              -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} \
              -DWINDOWS_SDK_PATH=$WINDOWS_SDK_PATH \
              -DCMAKE_TOOLCHAIN_FILE=../cmake/LinuxCrosscompile.cmake
            ninja
          '

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MinecraftClient-${{ matrix.configuration }}
          path: build
